DROP TABLE IF EXISTS playlist_chanson;
DROP TABLE IF EXISTS playlist;
DROP TABLE IF EXISTS chanson;
DROP TABLE IF EXISTS artiste;

CREATE TABLE artiste (
                         id_artiste SERIAL PRIMARY KEY,
                         nom VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE chanson (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         titre VARCHAR(200) NOT NULL,
                         album VARCHAR(200),
                         annee INTEGER CHECK (annee BETWEEN 1900 AND 2100),
                         genre VARCHAR(50) NOT NULL,
                         duree_sec INTEGER CHECK (duree_sec > 0),
                         ecoutes INTEGER DEFAULT 0 CHECK (ecoutes >= 0),
                         id_artiste INTEGER NOT NULL,

                         CONSTRAINT fk_chanson_artiste
                             FOREIGN KEY (id_artiste)
                                 REFERENCES artiste(id_artiste)
                                 ON DELETE RESTRICT
);

CREATE TABLE playlist (
                         id_playlist BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nom VARCHAR(150) NOT NULL UNIQUE,
                         date_creation DATE NOT NULL
);

CREATE TABLE playlist_chanson (
                         id_playlist BIGINT NOT NULL,
                         id_chanson BIGINT NOT NULL,
                         position INTEGER NOT NULL,
                         PRIMARY KEY (id_playlist, id_chanson),

                         CONSTRAINT fk_playlist_chanson_playlist
                             FOREIGN KEY (id_playlist)
                                 REFERENCES playlist(id_playlist)
                                 ON DELETE CASCADE,

                         CONSTRAINT fk_playlist_chanson_chanson
                             FOREIGN KEY (id_chanson)
                                 REFERENCES chanson(id)
                                 ON DELETE CASCADE
);
