package org.example.spotifylab.dao;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public final class InitialiseurBase {

    private static final String CHEMIN_CSV = "/org/example/spotifylab/data/chansons.csv";
    private static final Path CHEMIN_CSV_PROJET = Path.of(
            "src/main/resources/org/example/spotifylab/data/chansons.csv"
    );
    private static boolean dejaInitialisee = false;

    private InitialiseurBase() {
    }

    public static void initialiserSiNecessaire() throws SQLException {
        if (dejaInitialisee) {
            return;
        }

        try (Connection connexion = ConnexionBase.obtenirConnexion()) {
            creerTables(connexion);
            if (tableChansonVide(connexion)) {
                peuplerDepuisCsv(connexion);
            }
            dejaInitialisee = true;
        }
    }

    private static void creerTables(Connection connexion) throws SQLException {
        String creerArtiste = """
                CREATE TABLE IF NOT EXISTS artiste (
                    id_artiste SERIAL PRIMARY KEY,
                    nom VARCHAR(150) NOT NULL UNIQUE
                )
                """;

        String creerChanson = """
                CREATE TABLE IF NOT EXISTS chanson (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    titre VARCHAR(200) NOT NULL,
                    album VARCHAR(200),
                    annee INTEGER CHECK (annee BETWEEN 1900 AND 2100),
                    genre VARCHAR(50) NOT NULL,
                    duree_sec INTEGER CHECK (duree_sec > 0),
                    ecoutes INTEGER DEFAULT 0 CHECK (ecoutes >= 0),
                    id_artiste INTEGER NOT NULL,
                    CONSTRAINT fk_chanson_artiste
                        FOREIGN KEY (id_artiste)
                        REFERENCES artiste(id_artiste)
                        ON DELETE RESTRICT
                )
                """;

        try (Statement requete = connexion.createStatement()) {
            requete.executeUpdate(creerArtiste);
            requete.executeUpdate(creerChanson);
            requete.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS playlist (
                        id_playlist BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nom VARCHAR(150) NOT NULL UNIQUE,
                        date_creation DATE NOT NULL
                    )
                    """);
            requete.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS playlist_chanson (
                        id_playlist BIGINT NOT NULL,
                        id_chanson BIGINT NOT NULL,
                        position INTEGER NOT NULL,
                        PRIMARY KEY (id_playlist, id_chanson),
                        CONSTRAINT fk_playlist_chanson_playlist
                            FOREIGN KEY (id_playlist)
                            REFERENCES playlist(id_playlist)
                            ON DELETE CASCADE,
                        CONSTRAINT fk_playlist_chanson_chanson
                            FOREIGN KEY (id_chanson)
                            REFERENCES chanson(id)
                            ON DELETE CASCADE
                    )
                    """);
        }
    }

    private static boolean tableChansonVide(Connection connexion) throws SQLException {
        String sql = "SELECT COUNT(*) AS total FROM chanson";
        try (PreparedStatement requete = connexion.prepareStatement(sql);
             ResultSet resultat = requete.executeQuery()) {
            resultat.next();
            return resultat.getInt("total") == 0;
        }
    }

    private static void peuplerDepuisCsv(Connection connexion) throws SQLException {
        connexion.setAutoCommit(false);
        try (InputStream fichier = ouvrirCsv()) {
            try (BufferedReader lecteur = new BufferedReader(new InputStreamReader(fichier, StandardCharsets.UTF_8))) {
                lecteur.readLine();
                String ligne;
                while ((ligne = lecteur.readLine()) != null) {
                    String[] colonnes = ligne.split(";", -1);
                    long idArtiste = trouverOuAjouterArtiste(connexion, colonnes[2]);
                    ajouterChanson(connexion, colonnes, idArtiste);
                }
            }

            ajusterSequenceChanson(connexion);
            connexion.commit();
        } catch (IOException | SQLException exception) {
            connexion.rollback();
            throw new SQLException("Impossible de peupler la base depuis le CSV.", exception);
        } finally {
            connexion.setAutoCommit(true);
        }
    }

    private static InputStream ouvrirCsv() throws SQLException {
        InputStream fichier = InitialiseurBase.class.getResourceAsStream(CHEMIN_CSV);
        if (fichier != null) {
            return fichier;
        }

        try {
            return Files.newInputStream(CHEMIN_CSV_PROJET);
        } catch (IOException exception) {
            throw new SQLException("Fichier CSV introuvable: " + CHEMIN_CSV_PROJET, exception);
        }
    }

    private static long trouverOuAjouterArtiste(Connection connexion, String nom) throws SQLException {
        String inserer = """
                INSERT INTO artiste (nom)
                VALUES (?)
                ON CONFLICT (nom) DO UPDATE SET nom = EXCLUDED.nom
                RETURNING id_artiste
                """;

        try (PreparedStatement requete = connexion.prepareStatement(inserer)) {
            requete.setString(1, nom);
            try (ResultSet resultat = requete.executeQuery()) {
                resultat.next();
                return resultat.getLong("id_artiste");
            }
        }
    }

    private static void ajouterChanson(Connection connexion, String[] colonnes, long idArtiste) throws SQLException {
        String sql = """
                INSERT INTO chanson (id, titre, album, annee, genre, duree_sec, ecoutes, id_artiste)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT (id) DO NOTHING
                """;

        try (PreparedStatement requete = connexion.prepareStatement(sql)) {
            requete.setLong(1, Long.parseLong(colonnes[0]));
            requete.setString(2, colonnes[1]);
            requete.setString(3, colonnes[3]);
            requete.setInt(4, Integer.parseInt(colonnes[4]));
            requete.setString(5, colonnes[5]);
            requete.setInt(6, Integer.parseInt(colonnes[6]));
            requete.setInt(7, Integer.parseInt(colonnes[7]));
            requete.setLong(8, idArtiste);
            requete.executeUpdate();
        }
    }

    private static void ajusterSequenceChanson(Connection connexion) throws SQLException {
        String sql = "SELECT setval(pg_get_serial_sequence('chanson', 'id'), COALESCE(MAX(id), 1)) FROM chanson";
        try (PreparedStatement requete = connexion.prepareStatement(sql)) {
            requete.executeQuery();
        }
    }
}
